### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Import Modules
import os
import pandas as pd

#Find Current Path & List of Files/Folders in Current Path
current_path = os.getcwd()
current_directory = os.listdir()

#Loop Through List of Files/Folders in Current Path
for item in current_directory:
    
    #Set Condtion for Folder Containing School District Data
    if item.lower().find('school') >= 0 and item.lower().find('ipynb') == -1:

        #Loop Through List of Files/Folders in School District Data Folder
        for data in os.listdir(os.path.join(current_path, item)):
            
            #Set Condition for School Data CSV File
            if data.lower().find('school') >= 0 and data.lower().find('csv') >= 0:

                #Define Path Variable for School Data CSV File
                school_input = os.path.join(current_path, item, data)
                
            #Set Condition for Student Data CSV File
            elif data.lower().find('student') >= 0 and data.lower().find('csv') >= 0:

                #Define Path Variable for School Data CSV File
                student_input = os.path.join(current_path, item, data)

#Read School & Student CSV Files into Pandas Data Frames
school_data = pd.read_csv(school_input)
student_data = pd.read_csv(student_input)

#Merge School & Student Data Frames into Combined Data Frame
school_student_combined = pd.merge(student_data, school_data, how="left", on=["school_name", "school_name"])

#Display Merged Data Frame
school_student_combined

,Student ID,student_name,gender,grade,school_name,reading_score,math_score,School ID,type,size,budget
0,0,Paul Bradley,M,9th,Huang High School,66,79,0,District,2917,1910635
1,1,Victor Smith,M,12th,Huang High School,94,61,0,District,2917,1910635
2,2,Kevin Rodriguez,M,12th,Huang High School,90,60,0,District,2917,1910635
3,3,Dr. Richard Scott,M,12th,Huang High School,67,58,0,District,2917,1910635
4,4,Bonnie Ray,F,9th,Huang High School,97,84,0,District,2917,1910635
5,5,Bryan Miranda,M,9th,Huang High School,94,94,0,District,2917,1910635
6,6,Sheena Carter,F,11th,Huang High School,82,80,0,District,2917,1910635
7,7,Nicole Baker,F,12th,Huang High School,96,69,0,District,2917,1910635
8,8,Michael Roth,M,10th,Huang High School,95,87,0,District,2917,1910635
9,9,Matthew Greene,M,10th,Huang High School,96,84,0,District,2917,1910635
10,10,Andrew Alexander,M,10th,Huang High School,90,70,0,District,2917,1910635
11,11,Daniel Cooper,M,10th,Huang High School,78,77,0,District,2917,1910635
12,12,Brittney Walker,F,9th,Huang High School,64,79,0,District,2917,1910635
13,13,William Long,M,9th,Huang High School,71,79,0,District,2917,1910635
14,14,Tammy Hebert,F,10th,Huang High School,85,67,0,District,2917,1910635
15,15,Dr. Jordan Carson,M,11th,Huang High School,94,88,0,District,2917,1910635
16,16,Donald Zamora,M,9th,Huang High School,88,55,0,District,2917,1910635
17,17,Kimberly Santiago,F,9th,Huang High School,74,75,0,District,2917,1910635
18,18,Kevin Stevens,M,9th,Huang High School,64,69,0,District,2917,1910635
19,19,Brandi Lyons,F,9th,Huang High School,89,80,0,District,2917,1910635
20,20,Lisa Davis,F,10th,Huang High School,91,89,0,District,2917,1910635
21,21,Kristen Lopez,F,10th,Huang High School,90,77,0,District,2917,1910635
22,22,Kimberly Stewart,F,11th,Huang High School,99,84,0,District,2917,1910635
23,23,Christopher Parker,M,9th,Huang High School,81,68,0,District,2917,1910635
24,24,Chelsea Griffith,F,11th,Huang High School,85,73,0,District,2917,1910635
25,25,Cesar Morris,M,9th,Huang High School,92,70,0,District,2917,1910635
26,26,Melanie Decker,F,9th,Huang High School,63,85,0,District,2917,1910635
27,27,Tracey Oconnor,F,10th,Huang High School,80,58,0,District,2917,1910635
28,28,Kelly James,F,11th,Huang High School,73,55,0,District,2917,1910635
29,29,Nicole Brown,F,12th,Huang High School,90,88,0,District,2917,1910635
...,...,...,...,...,...,...,...,...,...,...,...
39140,39140,Cheyenne Hernandez,F,9th,Thomas High School,76,99,14,Charter,1635,1043130
39141,39141,Jonathan Sullivan,M,10th,Thomas High School,86,93,14,Charter,1635,1043130
39142,39142,Deborah Higgins DDS,F,10th,Thomas High School,96,83,14,Charter,1635,1043130
39143,39143,Steven Jackson,M,11th,Thomas High School,71,93,14,Charter,1635,1043130
39144,39144,Cristian Webster,M,12th,Thomas High School,77,87,14,Charter,1635,1043130
39145,39145,Audrey Fry,F,10th,Thomas High School,94,74,14,Charter,1635,1043130
39146,39146,Michael Carroll,M,9th,Thomas High School,69,95,14,Charter,1635,1043130
39147,39147,Raymond Hawkins,M,10th,Thomas High School,88,81,14,Charter,1635,1043130
39148,39148,Christopher Wilson,M,10th,Thomas High School,89,89,14,Charter,1635,1043130
39149,39149,Glenda Fletcher,F,11th,Thomas High School,82,93,14,Charter,1635,1043130
39150,39150,Jennifer Hamilton,F,11th,Thomas High School,80,75,14,Charter,1635,1043130
39151,39151,Shannon Williams,F,10th,Thomas High School,84,73,14,Charter,1635,1043130
39152,39152,Lori Moore,F,9th,Thomas High School,98,84,14,Charter,1635,1043130
39153,39153,William Hubbard,M,9th,Thomas High School,80,75,14,Charter,1635,1043130
39154,39154,Bradley Johnson,M,12th,Thomas High School,91,71,14,Charter,1635,1043130
39155,39155,John Brooks,M,10th,Thomas High School,92,98,14,Charter,1635,1043130
39156,39156,Stephanie Contreras,F,11th,Thomas High School,79,95,14,Charter,1635,1043130
39157,39157,Kristen Gonzalez,F,9th,Thomas High School,79,94,14,Charter,1635,1043130
39158,39158,Kari Holloway,F,10th,Thomas High School,87,90,14,Charter,1635,1043130
39159,39159,Kimberly Cabrera,F,11th,Thomas High School,85,72,14,Charter,1635,1043130
39160,39160,Katie Weaver,F,11th,Thomas High School,89,86,14,Charter,1635,1043130
39161,39161,April Reyes,F,10th,Thomas High School,70,84,14,Charter,1635,1043130
39162,39162,Derek Weeks,M,12th,Thomas High School,94,77,14,Charter,1635,1043130
39163,39163,John Reese,M,11th,Thomas High School,90,75,14,Charter,1635,1043130
39164,39164,Joseph Anthony,M,9th,Thomas High School,97,76,14,Charter,1635,1043130
39165,39165,Donna Howard,F,12th,Thomas High School,99,90,14,Charter,1635,1043130
39166,39166,Dawn Bell,F,10th,Thomas High School,95,70,14,Charter,1635,1043130
39167,39167,Rebecca Tanner,F,9th,Thomas High School,73,84,14,Charter,1635,1043130
39168,39168,Desiree Kidd,F,10th,Thomas High School,99,90,14,Charter,1635,1043130
39169,39169,Carolyn Jackson,F,11th,Thomas High School,95,75,14,Charter,1635,1043130

## District Summary

* Calculate the total number of schools

* Calculate the total number of students

* Calculate the total budget

* Calculate the average math score 

* Calculate the average reading score

* Calculate the overall passing rate (overall average score), i.e. (avg. math score + avg. reading score)/2

* Calculate the percentage of students with a passing math score (70 or greater)

* Calculate the percentage of students with a passing reading score (70 or greater)

* Create a dataframe to hold the above results

* Optional: give the displayed data cleaner formatting

In [2]:
#Calculate Total Number of Schools
total_schools = school_student_combined['school_name'].nunique()

#Caclculate Total Number of Students
total_students = school_student_combined['school_name'].count()

#Find Budgets for Each School & Calculate Total Budget
unique_budgets = school_student_combined['budget'].unique()

total_budget = unique_budgets.sum()

#Calculate Average Math & Reading Scores
math_avg = school_student_combined['math_score'].mean()
read_avg = school_student_combined['reading_score'].mean()

#Calculate Student Percentage Passing Math & Reading
math_pass = school_student_combined[school_student_combined['math_score'] >= 70]
read_pass = school_student_combined[school_student_combined['reading_score'] >= 70]

math_pct = ((math_pass['math_score'].count()) / total_students) * 100
read_pct = ((read_pass['reading_score'].count()) / total_students) * 100

#Calculate Overall Student Percentage Passing
overall_pass = (math_pct + read_pct) / 2

#Create Data Frame to Display District Summary
district_summary = pd.DataFrame({'Total Schools': [total_schools], 'Total Students': [format(total_students, ',d')],
                                 'Total Budget': ['${:,.2f}'.format(total_budget)],
                                 'Average Math Score': [round(math_avg, 3)],
                                 'Average Reading Score': [round(read_avg, 3)],
                                 '% Passing Math': [round(math_pct, 3)], '% Passing Reading': [round(read_pct, 3)],
                                 '% Overall Passing Rate': [round(overall_pass, 3)]})

#Display District Summary Data
district_summary

,Total Schools,Total Students,Total Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing Rate
0,15,"39,170","$24,649,428.00",78.985,81.878,74.981,85.805,80.393

## School Summary

* Create an overview table that summarizes key metrics about each school, including:
  * School Name
  * School Type
  * Total Students
  * Total School Budget
  * Per Student Budget
  * Average Math Score
  * Average Reading Score
  * % Passing Math
  * % Passing Reading
  * Overall Passing Rate (Average of the above two)
  
* Create a dataframe to hold the above results

## Top Performing Schools (By Passing Rate)

* Sort and display the top five schools in overall passing rate

In [4]:
#Split Combined Data Frame into Groups by School Name
school_groups = school_student_combined.groupby('school_name')

#Create Data Frame to Display School Summary
school_summary = pd.DataFrame({'School Type': [], 'Total Students': [], 'Total Budget': [], 'Per Student Budget': [],
                               'Average Math Score': [], 'Average Reading Score': [], '% Passing Math': [],
                               '% Passing Reading': [], '% Overall Passing Rate': []})

#Initialize Variables for School Metric Data
school_name = []
school_type = []
total_students = []
total_budget = []
student_budget = []
math_avg = []
read_avg = []
math_pct = []
read_pct = []
overall_pass = []

#Loop Through Key-Value Pairs for School Names & Associated Data Groups
for group_name, group_data in school_groups:
    
    #Assign School Name to Variable
    school_name.append(group_name)
    
    #Find School Type
    school_class = group_data['type'].unique()
    
    school_type.append(school_class[-1])
    
    #Calculate Total Students
    total_students.append(group_data['school_name'].count())
    
    #Find Total School Budget
    budget_amount = group_data['budget'].unique()
    
    total_budget.append(budget_amount[-1])
    
    #Calculate Budget Per Student
    student_budget.append(total_budget[-1] / total_students[-1])
    
    #Calculate Average Math & Reading Scores
    math_avg.append(group_data['math_score'].mean())
    read_avg.append(group_data['reading_score'].mean())
    
    #Calculate Student Percentage Passing Math & Reading
    math_pass = group_data[group_data['math_score'] >= 70]
    read_pass = group_data[group_data['reading_score'] >= 70]

    math_pct.append(((math_pass['math_score'].count()) / total_students[-1]) * 100)
    read_pct.append(((read_pass['reading_score'].count()) / total_students[-1]) * 100)
    
    #Calculate Overall Student Percentage Passing
    overall_pass.append((math_pct[-1] + read_pct[-1]) / 2)
    
#Append Individual School Data to School Summary Data Frame
school_summary = pd.DataFrame({'School Type': school_type, 'Total Students': [format(item, ',d') for item in total_students],
                               'Total Budget': ['${:,.2f}'.format(item) for item in total_budget],
                               'Per Student Budget': ['${:,.2f}'.format(item) for item in student_budget],
                               'Average Math Score': [round(item, 3) for item in math_avg],
                               'Average Reading Score': [round(item, 3) for item in read_avg],
                               '% Passing Math': [round(item, 3) for item in math_pct],
                               '% Passing Reading': [round(item, 3) for item in read_pct],
                               '% Overall Passing Rate': [round(item, 3) for item in overall_pass]}, school_name)

school_summary

,School Type,Total Students,Total Budget,Per Student Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing Rate
Bailey High School,District,"4,976","$3,124,928.00",$628.00,77.048,81.034,66.680,81.933,74.307
Cabrera High School,Charter,"1,858","$1,081,356.00",$582.00,83.062,83.976,94.133,97.040,95.587
Figueroa High School,District,"2,949","$1,884,411.00",$639.00,76.712,81.158,65.988,80.739,73.364
Ford High School,District,"2,739","$1,763,916.00",$644.00,77.103,80.746,68.310,79.299,73.804
Griffin High School,Charter,"1,468","$917,500.00",$625.00,83.351,83.817,93.392,97.139,95.266
Hernandez High School,District,"4,635","$3,022,020.00",$652.00,77.290,80.934,66.753,80.863,73.808
Holden High School,Charter,427,"$248,087.00",$581.00,83.803,83.815,92.506,96.253,94.379
Huang High School,District,"2,917","$1,910,635.00",$655.00,76.629,81.183,65.684,81.316,73.500
Johnson High School,District,"4,761","$3,094,650.00",$650.00,77.072,80.966,66.058,81.222,73.640
Pena High School,Charter,962,"$585,858.00",$609.00,83.840,84.045,94.595,95.946,95.270
Rodriguez High School,District,"3,999","$2,547,363.00",$637.00,76.843,80.745,66.367,80.220,73.293
Shelton High School,Charter,"1,761","$1,056,600.00",$600.00,83.359,83.726,93.867,95.855,94.861
Thomas High School,Charter,"1,635","$1,043,130.00",$638.00,83.418,83.849,93.272,97.309,95.291
Wilson High School,Charter,"2,283","$1,319,574.00",$578.00,83.274,83.989,93.868,96.540,95.204
Wright High School,Charter,"1,800","$1,049,400.00",$583.00,83.682,83.955,93.333,96.611,94.972

## Bottom Performing Schools (By Passing Rate)

* Sort and display the five worst-performing schools

## Math Scores by Grade

* Create a table that lists the average Reading Score for students of each grade level (9th, 10th, 11th, 12th) at each school.

  * Create a pandas series for each grade. Hint: use a conditional statement.
  
  * Group each series by school
  
  * Combine the series into a dataframe
  
  * Optional: give the displayed data cleaner formatting

## Reading Score by Grade

* Perform the same operations as above for reading scores

## Scores by School Spending

* Create a table that breaks down school performances based on average Spending Ranges (Per Student). Use 4 reasonable bins to group school spending. Include in the table each of the following:
  * Average Math Score
  * Average Reading Score
  * % Passing Math
  * % Passing Reading
  * Overall Passing Rate (Average of the above two)

In [ ]:
# Sample bins. Feel free to create your own bins.
spending_bins = [0, 585, 615, 645, 675]
group_names = ["<$585", "$585-615", "$615-645", "$645-675"]

## Scores by School Size

* Perform the same operations as above, based on school size.

In [ ]:
# Sample bins. Feel free to create your own bins.
size_bins = [0, 1000, 2000, 5000]
group_names = ["Small (<1000)", "Medium (1000-2000)", "Large (2000-5000)"]

## Scores by School Type

* Perform the same operations as above, based on school type.